# Generated by Django 3.2.16 on 2022-10-17 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_cloudspotlicense', '0002_cloudspotcompany_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudspotcompany',
            name='users',
            field=models.ManyToManyField(related_name='available_companies', to='django_cloudspotlicense.CloudspotUser'),
        ),
    ]
