
# This file was generated by 'versioneer.py' (0.26) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-06-12T12:21:28-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "cfc6fcc09d45e6a1c29cafd71a8ac609f7883752",
 "version": "0.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
