
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-06-14T08:41:09-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "0708088bbbc46e44dc4ba05cb5aadb1e88ad46d3",
 "version": "v1.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
