
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-06-13T14:18:36+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "d5d663099e0f5bcee5257b3b3fae358c94c07b4c",
 "version": "7.28.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
