commands=[
    'SELECT COUNT(*) FROM LIGHTSKY',
    'SELECT UID,BIND FROM BIND WHERE UID = "{}"',
    'SELECT UID, GRADE, JOB ,ABOUT FROM LIGHTSKY WHERE UID = "{}"',
    'SELECT UID, GRADE, JOB ,ABOUT from LIGHTSKY WHERE rowid={}',
    'SELECT COUNT(*) FROM BIND',
    'UPDATE LIGHTSKY SET GRADE=?,JOB=?,ABOUT=? WHERE UID=?',
    'INSERT INTO LIGHTSKY (UID,GRADE,JOB,ABOUT) VALUES (?,?,?,?)',
    'INSERT INTO BIND (UID,BIND) VALUES (?,?)',
    'DELETE FROM LIGHTSKY WHERE UID=?',
    'VACUUM']

new_c={
    'COUNT_MAIN':'SELECT COUNT(*) FROM LIGHTSKY',
    'CHECK_BIND':'SELECT UID,BIND FROM BIND WHERE UID = "{}"',
    'QUERYUID':'SELECT UID, GRADE, JOB ,ABOUT FROM LIGHTSKY WHERE UID = "{}"',
    'QUERYROW':'SELECT UID, GRADE, JOB ,ABOUT from LIGHTSKY WHERE rowid={}',
    'COUNT_BIND':'SELECT COUNT(*) FROM BIND',
    'ATEST_MAIN_2':'UPDATE LIGHTSKY SET GRADE=?,JOB=?,ABOUT=? WHERE UID=?',
    'ATEST_MAIN_1':'INSERT INTO LIGHTSKY (UID,GRADE,JOB,ABOUT) VALUES (?,?,?,?)',
    'ATEST_BIND_2':'UPDATE BIND SET BIND=? WHERE UID=?',
    'ATEST_BIND_1':'INSERT INTO BIND (UID,BIND) VALUES (?,?)',
    'DEL_MAIN':'DELETE FROM LIGHTSKY WHERE UID=?',
    'DEL_BIND':'DELETE FROM BIND WHERE UID=?',
    'CLEAN':'VACUUM'}

tablemaker=[
    """CREATE TABLE "ACTION" (
	"ABOUT"	TEXT
)""",
    """CREATE TABLE "BIND" (
	"UID"	TEXT NOT NULL,
	"BIND"	TEXT NOT NULL,
	PRIMARY KEY("UID")
)""",
    """
CREATE TABLE "LIGHTSKY" (
	"UID"	TEXT NOT NULL,
	"GRADE"	INTEGER,
	"JOB"   INTEGER,
	"ABOUT" TEXT,
	PRIMARY KEY("UID")
)"""]
