from typing import Union, overload

from Table import(
    ArrayTable
)

def tic()->None:...
def toc()->None:...

class Engine:
    def __init__(self,name:str) -> None: ...
    def nextstep(self)->None:...
    def countnodes(self)->None:...

    
    @property
    def components(self)->dict:...
    """
    get all the componets of the engine
    """

    @property
    def tnow(self)->float:...

    def init(self)->None:...

    @property
    def CFL(self)->float:...
    

class Port:
    def __init__(self) -> None: ...

class SensorPort(Port):
    def __init__(self) -> None: ...
    
class FlowPort(Port):
    def __init__(self) -> None: ...

class Sensor:
    def __init__(self) -> None: ...
    def connect(self,SensorPort)->Sensor:...

    @property
    def data(self):...


class Component:
    def __init__(self,engine:Engine) -> None: ...

    def getport(self,portid:int)->Port:...

    def getport(self,varname:str)->SensorPort:...

    def addtimedependentpara(self,var:str,table:ArrayTable)->None:...

    def clone(self)->Component:...

    def clone(self,times:int)->list(Component):...


class Connection(Component):
    def __init__(self, engine: Engine) -> None: ...

    def connect(self,p1:Port,P2:Port)->None:...

    def connect(self,pown:Port)->None:...

class References:
    def __init__(self) -> None: ...

class specie:
    def __init__(self) -> None: ...

class species(specie):
    def __init__(self,data) -> None: ...