class ArrayTable:
    def __init__(self,row:int,col:int) -> None: ...

    def init(self,filename:str)->ArrayTable:...

    def show(self)-> None: ...

    def plot(self)->None:...

    def interp1(self,x:float,coly:int,colx:int,type:int)->None:...

    
    def findMaximum(self,col:int,order:int)->None:...
    """
    find local Maximum data index of an order
    """

    @property
    def table(self)->list:...

    def append(self)->bool:...

    def open(self)->None:...

    def write2file(self,filename:str,type)->None:...


