from Engine import Framework
from Engine.Framework import Connection,Engine
from Engine import Table

def setcompremapavi(file:str,speedscale:float, massscale:float, prscale:float, effscale:float)->None:...

def setturmapavi(file:str,speedscale:float, massscale:float, prscale:float, effscale:float)->None:...

def masscom(speed:float,pi:float,num:int)->float:...

def effcom(speed:float,pi:float,num:int)->float:...

def masstur(speed:float,pi:float,num:int)->float:...

def efftur(speed:float,pi:float,num:int)->float:...

class Map(Framework.References):
    def __init__(self) -> None: ...

    def getline(self,speed:float)->Table.ArrayTable:...

class CompressorMap(Map):
    def __init__(self) -> None: ...

class TurbineMap(Map):
    def __init__(self) -> None: ...

