from Engine import Framework
from Engine.Framework import Connection,Engine,References
from Engine.Table import ArrayTable

class ValveLift(References):
    def __init__(self) -> None: ...
    def init(self,table:ArrayTable)->ValveLift:...
    def init(self,x_max:float,tau:float)->ValveLift:...
    def move_timing(self,open_timing:float,close_timing:float)->None:...

class ValveSimple(Connection):
    def __init__(self, engine: Engine) -> None: ...
    def init(self,Area:str,type:int)->ValveSimple:...

class Valve(Connection):
    def __init__(self, engine: Engine) -> None: ...
    def init(self,ValveLift:ValveLift,valveDiameter:float,SigmaIn:float,_flow_coeff:None)->Valve:...
    @property
    def lift(self)->ValveLift:...

    