# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: traininginforequest.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19traininginforequest.proto\x12\x1ewatson_core_data_model.runtime\"*\n\x13TrainingInfoRequest\x12\x13\n\x0btraining_id\x18\x01 \x01(\tBu\n\x1a\x63om.ibm.watson.runtime.nlpP\x01ZUgithub.ibm.com/ai-foundation/watson_nlp_runtime_client/watson_core_data_model/runtimeb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'traininginforequest_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\032com.ibm.watson.runtime.nlpP\001ZUgithub.ibm.com/ai-foundation/watson_nlp_runtime_client/watson_core_data_model/runtime'
  _TRAININGINFOREQUEST._serialized_start=61
  _TRAININGINFOREQUEST._serialized_end=103
# @@protoc_insertion_point(module_scope)
