
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-06-09T19:58:01-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "7e200bf2efd27ff20480f6a08c9c1356528b4f13",
 "version": "0.4.26"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
