from .pc_for_chatglm import ChatGlmPreProcessor
from .question_answer_pc import QuestionAnswerPreProcessor
from .text_classification_pc import TextClassificationPreProcessor
from .pc_for_alpaca import AlpacaPreProcessor
from .pc_for_llama_cn import VicunaPreProcessor