
# This file was generated by 'versioneer.py' (0.26) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-06-09T10:16:49+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "d7e4a312b9c749d530f7cf3c06068857ab6b2fe2",
 "version": "0.4.0.post0.dev19"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
