
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-06-13T15:53:23+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "fea6543a7922ee72c7000cf2331525dc07f39db1",
 "version": "6.5.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
