# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api_keys_objects.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x61pi_keys_objects.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"k\n\x06\x41piKey\x12\x0e\n\x06key_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12.\n\ncreated_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp*T\n\x05\x45rror\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x12\n\x0eNOT_AUTHORIZED\x10\x01\x12\x13\n\x0fINVALID_API_KEY\x10\x02\x12\x15\n\x11\x41PI_KEY_NOT_FOUND\x10\x03\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api_keys_objects_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ERROR._serialized_start=168
  _ERROR._serialized_end=252
  _APIKEY._serialized_start=59
  _APIKEY._serialized_end=166
# @@protoc_insertion_point(module_scope)
