# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions

InternalServerErrorResponseBodyCode = typing.Union[typing_extensions.Literal["internal_server_error"]]
