from typing import Dict

def load_asset(path): ...
def mapping_bimcv_covid19_negative_ct_rotate_transforms() -> Dict[str, str]: ...
def mapping_bimcv_covid19_positive_ct_rotate_transforms() -> Dict[str, str]: ...
def mapping_bimcv_covid19_ct_rotate_transforms() -> Dict[str, str]: ...
