# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.2.21.dev0+g8cb52b4.d20230608'
__version_tuple__ = version_tuple = (0, 2, 21, 'dev0', 'g8cb52b4.d20230608')
