
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-06-09T17:44:34+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "6c61e21d85b67e399ef35c4a3fd03a51e16acb6c",
 "version": "0.57.1rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
