import numpy as np
import typing as tp
from .typing import LikePath, Spacing
from typing import Optional

def save_json_gz(data: tp.Dict, path: LikePath, *, compression: int = ...): ...
def load_json_gz(path: LikePath) -> tp.Dict: ...
def resolve_escape_char(string: str) -> str: ...
def remove_double_space(string: str) -> str: ...
def derepr_list(string) -> str: ...
def derepr_medical_evaluation_text(text: str) -> str: ...
def skip_empty(sequence) -> tp.List: ...
def derepr_CUIS(string) -> tp.List[str]: ...
def nifty2numpy(nifti_path: LikePath) -> np.ndarray: ...
def png2numpy(png_path: LikePath) -> np.ndarray: ...
def down_type(data: np.ndarray): ...
def spacing_from_nifty(nifti_path: LikePath) -> tp.Optional[Spacing]: ...
def spacing_from_tags(tags: tp.Optional[dict]) -> tp.Optional[Spacing]: ...
def parse_dicom_tags(tags: tp.Dict[str, tp.Any]) -> tp.Optional[tp.Union[dict, list]]: ...
def derepr_strings_list(string): ...
def open_from_tar(path: LikePath, subpath: LikePath): ...
def save_numpy(value, path, *, allow_pickle: bool = ..., fix_imports: bool = ..., compression: Optional[int] = ..., timestamp: Optional[int] = ...) -> None: ...
def load_numpy(path, *, allow_pickle: bool = ..., fix_imports: bool = ..., decompress: bool = ...): ...
