import typing as tp
from .typing import LikePath as LikePath
from _typeshed import Incomplete
from webdav3.client import Client

def get_sha1(path: LikePath) -> str: ...
def read_checksums(path: LikePath, sep: Incomplete | None = ...) -> tp.Dict[str, str]: ...
def webdav_download_file(client: Client, remote_path: LikePath, local_path: LikePath, sha1sum: tp.Optional[str] = ...) -> bool: ...
def webdav_download_all(root: LikePath, webdav_hostname: str, webdav_login: str, webdav_password: str): ...
