
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-06-11T09:11:18-0700",
 "dirty": true,
 "error": null,
 "full-revisionid": "b4812d83e038eae44309cc5462b5e2125d9dde5e",
 "version": "0.1.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
