from setuptools import setup

setup(
    name='liveramp_automation_framework',
    version='0.0.6',
    description='liveramp_automation_framework',
    author='Jasmine Qian',
    author_email='jasmine.qian@liveramp.com',
    packages=['liveramp_automation'],
    install_requires=[
        'pytest',
        'pytest-bdd',
        'pytest-playwright',
        'allure-pytest-bdd',
        'allure-python-commons',
        'google',
        'google-api-core',
        'google-auth',
        'google-cloud-bigquery',
        'google-cloud-core',
        'google-cloud-storage',
        'google-crc32c',
        'google-resumable-media',
        'googleapis-common-protos',
        'PyYAML',
        'pytest-json-report',
        'pytest-json',
        'pytest-xdist',
        'requests',
        'selenium==4.8.3',
        'pytest-bdd==6.1.1',
        'PyYAML==6.0',
        'webdriver-manager==3.8.6',
        'retrying==1.3.4',
    ],
)
