
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-06-11T19:41:10-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "a6868a59a18651bb99206abe427e488c57351133",
 "version": "0.0.176"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
