# coding: utf-8

# flake8: noqa

# import all models into this package
# if you have many models here with many references from one model to another this may
# raise a RecursionError
# to avoid this, import only the models that you directly need like:
# from songtradr_api_client_python.model.pet import Pet
# or import this package, but before doing it, use:
# import sys
# sys.setrecursionlimit(n)

from songtradr_api_client_python.model.category_medium_dto import CategoryMediumDTO
from songtradr_api_client_python.model.category_minimal_dto import CategoryMinimalDTO
from songtradr_api_client_python.model.config_access_dto import ConfigAccessDTO
from songtradr_api_client_python.model.config_identifier_dto import ConfigIdentifierDTO
from songtradr_api_client_python.model.contributor_type_dto import ContributorTypeDTO
from songtradr_api_client_python.model.error_response import ErrorResponse
from songtradr_api_client_python.model.field_summary_dto import FieldSummaryDTO
from songtradr_api_client_python.model.file_dto import FileDTO
from songtradr_api_client_python.model.file_list_dto import FileListDTO
from songtradr_api_client_python.model.file_minimal_with_url_dto import FileMinimalWithUrlDTO
from songtradr_api_client_python.model.file_small_dto import FileSmallDTO
from songtradr_api_client_python.model.file_upload_dto import FileUploadDTO
from songtradr_api_client_python.model.file_w_ith_url_dto import FileWIthUrlDTO
from songtradr_api_client_python.model.files_summary_dto import FilesSummaryDTO
from songtradr_api_client_python.model.forgot_password_dto import ForgotPasswordDTO
from songtradr_api_client_python.model.genre_dto import GenreDTO
from songtradr_api_client_python.model.genre_minimal_dto import GenreMinimalDTO
from songtradr_api_client_python.model.genres_summary_dto import GenresSummaryDTO
from songtradr_api_client_python.model.init_put_recording_audio_dto import InitPutRecordingAudioDTO
from songtradr_api_client_python.model.jwt_token_dto import JwtTokenDTO
from songtradr_api_client_python.model.login_dto import LoginDTO
from songtradr_api_client_python.model.musical_features_dto import MusicalFeaturesDTO
from songtradr_api_client_python.model.p_line_dto import PLineDTO
from songtradr_api_client_python.model.party_large_dto import PartyLargeDTO
from songtradr_api_client_python.model.party_small_dto import PartySmallDTO
from songtradr_api_client_python.model.playlist_large_dto import PlaylistLargeDTO
from songtradr_api_client_python.model.product_medium_dto import ProductMediumDTO
from songtradr_api_client_python.model.product_party_dto import ProductPartyDTO
from songtradr_api_client_python.model.recording_for_similarity_search_dto import RecordingForSimilaritySearchDTO
from songtradr_api_client_python.model.recording_genre_prediction_dto import RecordingGenrePredictionDTO
from songtradr_api_client_python.model.recording_large_dto import RecordingLargeDTO
from songtradr_api_client_python.model.recording_list_dto import RecordingListDTO
from songtradr_api_client_python.model.recording_medium_dto import RecordingMediumDTO
from songtradr_api_client_python.model.recording_minimal_with_musical_features_dto import RecordingMinimalWithMusicalFeaturesDTO
from songtradr_api_client_python.model.recording_minimal_with_taggrams_dto import RecordingMinimalWithTaggramsDTO
from songtradr_api_client_python.model.recording_minimal_with_tagstrengths_dto import RecordingMinimalWithTagstrengthsDTO
from songtradr_api_client_python.model.recording_party_dto import RecordingPartyDTO
from songtradr_api_client_python.model.recording_playlist_dto import RecordingPlaylistDTO
from songtradr_api_client_python.model.recording_small_dto import RecordingSmallDTO
from songtradr_api_client_python.model.recording_tag_small_dto import RecordingTagSmallDTO
from songtradr_api_client_python.model.save_file_recording_dto import SaveFileRecordingDTO
from songtradr_api_client_python.model.save_playlist_dto import SavePlaylistDTO
from songtradr_api_client_python.model.save_recording_genre_dto import SaveRecordingGenreDTO
from songtradr_api_client_python.model.save_recording_party_dto import SaveRecordingPartyDTO
from songtradr_api_client_python.model.save_recording_playlist_dto import SaveRecordingPlaylistDTO
from songtradr_api_client_python.model.save_recording_tag_dto import SaveRecordingTagDTO
from songtradr_api_client_python.model.save_referrer_dto import SaveReferrerDTO
from songtradr_api_client_python.model.save_taggrams_dto import SaveTaggramsDTO
from songtradr_api_client_python.model.save_user_dto import SaveUserDTO
from songtradr_api_client_python.model.search_filter_values_dto import SearchFilterValuesDTO
from songtradr_api_client_python.model.search_recording_granular_abstraction_dto import SearchRecordingGranularAbstractionDTO
from songtradr_api_client_python.model.search_recording_granular_dto import SearchRecordingGranularDTO
from songtradr_api_client_python.model.sign_up_dto import SignUpDTO
from songtradr_api_client_python.model.tag_dto import TagDTO
from songtradr_api_client_python.model.tag_small_dto import TagSmallDTO
from songtradr_api_client_python.model.taggram_dto import TaggramDTO
from songtradr_api_client_python.model.tags_summary_dto import TagsSummaryDTO
from songtradr_api_client_python.model.tagstrength_dto import TagstrengthDTO
from songtradr_api_client_python.model.title_dto import TitleDTO
from songtradr_api_client_python.model.token_request import TokenRequest
from songtradr_api_client_python.model.track_to_medium_product_dto import TrackToMediumProductDTO
from songtradr_api_client_python.model.update_password_dto import UpdatePasswordDTO
from songtradr_api_client_python.model.usage_dto import UsageDTO
from songtradr_api_client_python.model.user_dto import UserDTO
