from enum import Enum


class JobStatus(Enum):
    AUTHORIZING='AUTHORIZING'
    BUILDING='BUILDING'
    CANCELLED='CANCELLED'
    CREATED='CREATED'
    DONE='DONE'
    FAILED='FAILED'
    GENERATING='GENERATING'
    PUSHING='PUSHING'