# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/API.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protobuf import A2L_pb2 as protobuf_dot_A2L__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12protobuf/API.proto\x1a\x12protobuf/A2L.proto\"\x1d\n\x0eGetTreeRequest\x12\x0b\n\x03\x61\x32l\x18\x01 \x01(\t22\n\x03\x41\x32L\x12+\n\x07GetTree\x12\x0f.GetTreeRequest\x1a\r.RootNodeType\"\x00\x42\x0eZ\x0c./../pkg/a2lb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protobuf.API_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\014./../pkg/a2l'
  _GETTREEREQUEST._serialized_start=42
  _GETTREEREQUEST._serialized_end=71
  _A2L._serialized_start=73
  _A2L._serialized_end=123
# @@protoc_insertion_point(module_scope)
