# Generated by Django 4.1.7 on 2023-04-04 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_common_objects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commoncategory',
            name='model',
            field=models.CharField(max_length=100, verbose_name='所属模型'),
        ),
        migrations.AlterField(
            model_name='commonfieldconfig',
            name='model',
            field=models.CharField(max_length=100, verbose_name='所属模型'),
        ),
        migrations.AlterField(
            model_name='commontag',
            name='model',
            field=models.CharField(max_length=100, verbose_name='所属模型'),
        ),
    ]
