# Generated by Django 4.1.7 on 2023-04-07 16:58

from django.conf import settings
from django.db import migrations, models
import django_common_objects.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_common_objects', '0002_alter_commoncategory_model_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commoncategory',
            unique_together={('name', 'user')},
        ),
        migrations.AlterField(
            model_name='commoncategory',
            name='config',
            field=models.JSONField(blank=True, null=True, verbose_name='详细'),
        ),
    ]
