# coding: utf-8

"""


    Generated by: https://openapi-generator.tech
"""

import unittest
from unittest.mock import patch

import urllib3

import songtradr_api_client_python
from songtradr_api_client_python.paths.api_v1_user_update_password import post  # noqa: E501
from songtradr_api_client_python import configuration, schemas, api_client

from .. import ApiTestMixin


class TestApiV1UserUpdatePassword(ApiTestMixin, unittest.TestCase):
    """
    ApiV1UserUpdatePassword unit test stubs
        Update password by using the password reset token  # noqa: E501
    """
    _configuration = configuration.Configuration()

    def setUp(self):
        used_api_client = api_client.ApiClient(configuration=self._configuration)
        self.api = post.ApiForpost(api_client=used_api_client)  # noqa: E501

    def tearDown(self):
        pass

    response_status = 204






if __name__ == '__main__':
    unittest.main()
