# Generated by Django 4.0.3 on 2023-06-13 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EmailTemplate', '0005_emailtemplate_bcc_emailtemplate_cc'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='Subject')),
                ('body', models.TextField(verbose_name='Body')),
                ('from_email', models.CharField(max_length=255, verbose_name='From')),
                ('to_email', models.CharField(max_length=1000, verbose_name='To')),
                ('cc', models.CharField(blank=True, max_length=1000, null=True, verbose_name='CC')),
                ('bcc', models.CharField(blank=True, max_length=1000, null=True, verbose_name='BCC')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Sent At')),
                ('sent_status', models.BooleanField(default=False, verbose_name='Sent status')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Error message')),
                ('email_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmailTemplate.emailtemplate')),
            ],
        ),
    ]
