
# DO NOT EDIT THIS FILE -- AUTOGENERATED BY PANTS
# Target: src/ol_openedx_logging:logging_package

from setuptools import setup

setup(**{
    'description': 'An Open edX plugin to customize the logging configuration used by the edx-platform application',
    'entry_points': {
        'lms.djangoapp': [
            'ol_openedx_logging = ol_openedx_logging.app:EdxLoggingLMS',
        ],
        'cms.djangoapp': [
            'ol_openedx_logging = ol_openedx_logging.app:EdxLoggingCMS',
        ],
    },
    'install_requires': (
        'Django>2.0',
        'python-json-logger<3.0.0,>=2.0.2',
    ),
    'license': 'BSD-3-Clause',
    'name': 'ol-openedx-logging',
    'namespace_packages': (
    ),
    'package_data': {
    },
    'packages': (
        '',
        'ol_openedx_logging',
        'ol_openedx_logging.settings',
    ),
    'python_requires': '>=3.8',
    'version': '0.0.1',
})
