
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-06-09T11:55:16+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "3aedb65a24bbec4178ae2f04534d1eca8fffee16",
 "version": "0.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
