from enum import Enum


class JobStatus(Enum):
    CREATED='CREATED'
    AUTHORIZING='AUTHORIZING'
    GENERATING='GENERATING'
    BUILDING='BUILDING'
    PUSHING='PUSHING'
    DONE='DONE'
    CANCELLED='CANCELLED'
    FAILED='FAILED'