
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-06-14T13:32:22+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "e9434441b81235b23a61adfb3dab1910c6d6ebee",
 "version": "1.13.220"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
