
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-06-09T11:52:30+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "da63f74be071aac2eb73dc0bf1ee999a559f3ae6",
 "version": "0.50"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
