ARTIFACT_COBERTURA = "cobertura"
ARTIFACT_FILE = "file"
ARTIFACT_JOB = "job"
ARTIFACT_JUNIT = "junit"
ARTIFACT_PATH = "path"
ARTIFACT_VARIABLE = "variable"

ARTIFACT_TYPES = (
    ARTIFACT_COBERTURA,
    ARTIFACT_FILE,
    ARTIFACT_JOB,
    ARTIFACT_JUNIT,
    ARTIFACT_PATH,
    ARTIFACT_VARIABLE,
)
