
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-06-13T11:38:22+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "31dc34a5bb8607b01a71014b1c4445219600ca7c",
 "version": "0.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
